// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCountries() {
  return window['go']['main']['App']['GetCountries']();
}

export function GetRawRadios() {
  return window['go']['main']['App']['GetRawRadios']();
}

export function GetSavedMusicDirectory() {
  return window['go']['main']['App']['GetSavedMusicDirectory']();
}

export function GetStations(arg1) {
  return window['go']['main']['App']['GetStations'](arg1);
}

export function ListLocalMusics(arg1) {
  return window['go']['main']['App']['ListLocalMusics'](arg1);
}

export function ResolveYouTubeAudio(arg1) {
  return window['go']['main']['App']['ResolveYouTubeAudio'](arg1);
}

export function SaveRawRadios(arg1) {
  return window['go']['main']['App']['SaveRawRadios'](arg1);
}

export function SelectMusicDirectory() {
  return window['go']['main']['App']['SelectMusicDirectory']();
}
